kibot:
  version: 1

outputs:
  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: gerbers
    options:
      # generic layer options
      exclude_edge_layer: false
      #exclude_pads_from_silkscreen: false
      #plot_sheet_reference: false
      #plot_footprint_refs: true
      #plot_footprint_values: true
      #force_plot_invisible_refs_vals: false
      #tent_vias: true
      #line_width: 0.15

      # gerber options
      #use_aux_axis_as_origin: false
      #subtract_mask_from_silk: true
      #use_protel_extensions: false
      #gerber_precision: 4.5
      #create_gerber_job_file: true
      #use_gerber_x2_attributes: true
      #use_gerber_net_attributes: false

    layers:
      - 'Front'
      - '3.3V'
      - 'GND'
      - 'Back'
  - name: 'print_sch'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: .
    options:
      output: 'docs/svg/%f-%i%v.%x'
