# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"update_templates": "00_actions.ipynb",
         "sch_to_bom": "00_actions.ipynb",
         "bom_to_sch": "00_actions.ipynb",
         "test_notebooks": "01_test.ipynb",
         "get_git_root": "02_utilities.ipynb",
         "setup_test_repo": "02_utilities.ipynb",
         "get_project_name": "02_utilities.ipynb",
         "get_project_metadata": "02_utilities.ipynb",
         "get_schematic_path": "02_utilities.ipynb",
         "get_bom_path": "02_utilities.ipynb",
         "get_gitignore_list": "02_utilities.ipynb",
         "in_gitignore": "02_utilities.ipynb",
         "install_python_package": "02_utilities.ipynb"}

modules = ["actions.py",
           "test.py",
           "utilities.py"]

doc_url = "https://ryanfobel.github.io/kicad-helpers/"

git_url = "https://github.com/ryanfobel/kicad-helpers/tree/main/"

def custom_doc_links(name): return None
