# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_initialize_a_new_project.ipynb (unless otherwise specified).

__all__ = ['init_github_workflows']

# Cell
import os
import pkg_resources

import jinja2
from fastcore.script import *

from .core import get_project_root, get_project_name

# Cell
@call_parse
def init_github_workflows():
    src_path = os.path.abspath(pkg_resources.resource_filename('kicad_helpers', 'templates/build.yml'))

    root = get_project_root()
    dst_path = os.path.abspath(os.path.join(root,
                                            ".github",
                                            "workflows",
                                            "build.yml"
    ))
    # Create the `.github/workflows` directory if it doesn't exist
    os.makedirs(os.path.split(dst_path)[0], exist_ok=True)

    print(f"src_path={src_path}")
    print(f"dst_path={dst_path}")

    if os.path.exists(dst_path):
        print(f"{dst_path} already exists")

    with open(src_path) as f:
        template = jinja2.Template(f.read())

    with open(dst_path, "w") as f:
        f.write(template.render(PROJECT_NAME=get_project_name()))